name: Filen Media Sync (Manual Only)

on:
  workflow_dispatch:  # Manual trigger only - no automatic schedule

jobs:
  sync-media:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install requests
      
      - name: Run sync script
        env:
          FILEN_API_KEY: ${{ secrets.FILEN_API_KEY }}
        run: |
          python scripts/sync_media.py
      
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add media_links.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update media links" && git push)